name: Build macos

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install xmake
        run: |
          curl -fsSL https://xmake.io/shget.text | bash
          source ~/.xmake/profile

      - name: Install dependencies (Homebrew)
        run: |
          brew update
          brew install luajit quill 

      - name: Update xrepo
        run: |
          source ~/.xmake/profile
          xrepo update-repo

      - name: Configure & Build
        run: |
          source ~/.xmake/profile
          xmake f -p macos -a arm64
          xmake -v
          xmake

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build-x86_64
          path: build/
